### ISSUE TITLE
EJS Support

### ISSUE THREAD

**Issue by ahvdesign** [zignd/HTML-CSS-Class-Completion#102]
Hello,

I was wondering if it is planned to support .ejs files the way HTML is handled. I work with Bootstrap and EJS but if I want to use this plugin I have to work in a sandbox HTML file for the plugin to work correctly and then copy/paste the HTML code into the EJS file. 

If this is something I can even do myself in one of the settings I would love to know! 

Thank you!

**Comment by zignd** [comment]
Are you sure it doesn't work? We implemented support for it a couple months ago, and I just tried it using this extension (https://marketplace.visualstudio.com/items?itemName=DigitalBrainstem.javascript-ejs-support) for the language mode and it worked. It should be noticed that you need the language mode for EJS for the support for it to work. My extension doesn't add new language modes, but instead makes use of existing ones.

**Comment by ahvdesign** [comment]
Ahh sorry I actually did not know about the language mode. Still fairly new at coding. I’ll check it out again and if I still have any issues I’ll give you a heads up. 😊
