### ISSUE TITLE
Extension hangs / freezes VS Code in big folders

### ISSUE THREAD

**Issue by Yanpas** [zignd/HTML-CSS-Class-Completion#85]
STR:
Download liberoffice master git (git clone git://anongit.freedesktop.org/libreoffice/core), open this folder in VS code. After some secs Vs code is frozen

**Comment by tabayomi** [comment]
Confirming this bug exists.  Strangely enough, it only started causing issues for me when I updated to VSCode 1.16. I had it installed and working previously without a problem. After I upgraded, VSCode started to freeze and after about 1min - it would crash. 

Here's the odd thing - it only happened when I opened a PHP app repo I've been working with for months without any issues. Other projects didn't cause a crash.  PHP project directory is by far the largest though, so that may be related. 

Details:
VSCode version: `1.16` and `1.16.1`
Platform: `Mac OS X Sierra (10.2.6)`
Steps to reproduce: `For me, opening my really large PHP app.` 
Other Extensions: `JSLint, ESLint, TSLint, PHP Extension Pack`

**Comment by aeschli** [comment]
@zingd The problem is that [workspace.openTextDocument](https://github.com/zignd/HTML-CSS-Class-Completion/blob/2a6c218c14718cd3ed5ca17bc077878dddee0567/src/parse-engine-gateway.ts#L8) is used for all css & html resources in the workspace.
The VSCode documentation, unfortunately, lacks to mention it, but opening a text document is costly and has side effects: The document is passed across process boundaries to interested language servers where it is validated.
I recommend doing the following instead. For each uri:
- check the already [open text documents](https://github.com/Microsoft/vscode/blob/f127ec349548fbdde7d681f221313c844660fa4d/src/vs/vscode.d.ts#L5125) and, if available, get the contents from there
- if not, acquire the file content with `fs.readFile`

If there is a need, we can look into providing additional API in VSCode to detect the language and file encoding. Please file issues! Thanks a lot!

**Comment by sandersu** [comment]
I have the same problem when opening a large angular project. 

VSCode version: 1.17.0 (1.17.0)
Platform: Mac OS X Sierra (10.12.6)
Steps to reproduce: For me, opening my really large PHP app.
Other Extensions: EditorConfig.EditorConfig, WallabyJs.wallaby-vscode, dbaeumer.vscode-eslint ,donjayamanne.githistory, felipecaputo.git-project-manager, formulahendry.auto-close-tag, liuji-jim.vue, mrmlnc.vscode-postcss-sorting, octref.vetur, robertohuertasm.vscode-icons, shinnn.stylelint, waderyan.gitblame

**Comment by fantasticfears** [comment]
Another confirm with a rather small size C++ project. Hang the main process.

VSCode 1.17.0 on macOS 10.12.6.

**Comment by zignd** [comment]
I guess this issue has been fixed in the latest update. Thanks to Erich Gamma for this great pull request #90.

**Comment by mcquiggd** [comment]
This is still happening for me on Ubuntu 16.04, VS Code 1.19.2, latest version of the extension at time of writing.

With the extension enabled, VS Code will periodically crash, taking out my whole session.
